<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_597937d82add6',
        'title' => 'Body Enhanced',
        'fields' => array(
            array(
                'key' => 'field_597937e615bf8',
                'label' => 'Body Enhanced',
                'name' => 'bodyEnhanced',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    '5979390d76e18' => array(
                        'key' => '5979390d76e18',
                        'name' => 'heading',
                        'label' => 'Heading',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_597943be45f60',
                                'label' => 'Heading Label',
                                'name' => 'heading_label',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5979390d76e1a',
                                'label' => 'Heading Type',
                                'name' => 'heading_type',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'h1' => 'Heading 1',
                                    'h2' => 'Heading 2',
                                    'h3' => 'Heading 3',
                                    'h4' => 'Heading 4',
                                    'h5: Heading 5' => 'h5: Heading 5',
                                    'h6' => 'Heading 6',
                                ),
                                'default_value' => array(
                                    0 => 'h1',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'array',
                                'placeholder' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5979391476e1c' => array(
                        'key' => '5979391476e1c',
                        'name' => 'text',
                        'label' => 'Text',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5979391476e1f',
                                'label' => 'Text',
                                'name' => 'text',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'basic',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '597fec48c1bf9' => array(
                        'key' => '597fec48c1bf9',
                        'name' => 'ad_space',
                        'label' => 'Ad Space',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_597fec48c1bfa',
                                'label' => 'Ad Image',
                                'name' => 'ad_image',
                                'type' => 'image',
                                'instructions' => 'Recommended Ad Size 864px x 280px',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_597fec48c1bfb',
                                'label' => 'Ad Heading',
                                'name' => 'ad_heading',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_597fec48c1bfc',
                                'label' => 'Ad Link',
                                'name' => 'ad_link',
                                'type' => 'url',
                                'instructions' => 'Link the banner to any page/URL. Leaving this blank will not add a link on the image.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '597937ee8a71b' => array(
                        'key' => '597937ee8a71b',
                        'name' => 'banner',
                        'label' => 'Banner',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5979382815bf9',
                                'label' => 'Banner Image',
                                'name' => 'banner_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_59793db35fbb3',
                                'label' => 'Banner Heading',
                                'name' => 'banner_heading',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_59793987b8c8c',
                                'label' => 'Banner Link',
                                'name' => 'banner_link',
                                'type' => 'url',
                                'instructions' => 'Link the banner to any page/URL. Leaving this blank will not add a link on the image.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '59794bd950ee7' => array(
                        'key' => '59794bd950ee7',
                        'name' => 'call_out_block',
                        'label' => 'Call Out Block',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_59794bd950eec',
                                'label' => 'Call Out Block Text',
                                'name' => 'call_out_block_text',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5979f5b4da58e' => array(
                        'key' => '5979f5b4da58e',
                        'name' => 'detail_block',
                        'label' => 'Detail Block',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5979f5b4da58f',
                                'label' => 'Detail Block Text',
                                'name' => 'detail_block_text',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '597ff21497edb' => array(
                        'key' => '597ff21497edb',
                        'name' => 'sponsor_logos',
                        'label' => 'Sponsor Logos',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_597ff26897edf',
                                'label' => 'Sponsor Block',
                                'name' => 'sponsor_block',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Add Sponsor',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_597ff27897ee0',
                                        'label' => 'Sponsor Image',
                                        'name' => 'sponsor_image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_597ff28897ee1',
                                        'label' => 'Sponsor Title',
                                        'name' => 'sponsor_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_597ff2aa97ee2',
                                        'label' => 'Sponsor URL',
                                        'name' => 'sponsor_url',
                                        'type' => 'url',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '597945eb0ff4b' => array(
                        'key' => '597945eb0ff4b',
                        'name' => 'button',
                        'label' => 'Single Button',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_597945eb0ff4c',
                                'label' => 'Button Label',
                                'name' => 'button_label',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_598334ce5f465',
                                'label' => 'Button Class',
                                'name' => 'button_class',
                                'type' => 'text',
                                'instructions' => 'Add a custom class name or attach the Popup Maker class',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_597946020ff4d',
                                'label' => 'Button Link',
                                'name' => 'button_link',
                                'type' => 'url',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_597946150ff4e',
                                'label' => 'Button Type',
                                'name' => 'button_type',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'primary' => 'Primary',
                                    'secondary' => 'Secondary',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_597946fbcb2f9',
                                'label' => 'Button Target',
                                'name' => 'button_target',
                                'type' => 'select',
                                'instructions' => 'The target attribute specifies where to open the linked document.',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    '_self' => 'Current Tab',
                                    '_blank' => 'New Tab',
                                ),
                                'default_value' => array(
                                    0 => '_self',
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_597948a94767b',
                                'label' => 'Button Position',
                                'name' => 'button_position',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'left' => 'Left',
                                    'center' => 'Center',
                                    'right' => 'Right',
                                    'full' => 'Full',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'left',
                                'layout' => 'vertical',
                                'return_format' => 'value',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5985f18137fc4' => array(
                        'key' => '5985f18137fc4',
                        'name' => 'multiple_button',
                        'label' => 'Multiple Buttons',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5985f3e4a9a95',
                                'label' => 'Align Buttons',
                                'name' => 'align_buttons',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'flex-start' => 'Align Left',
                                    'flex-end' => 'Align Right',
                                    'center' => 'Align Center',
                                    'space-between' => 'Align Space Between',
                                    'space-around' => 'Align Space Around',
                                ),
                                'default_value' => array(
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_5985f1bb37fcb',
                                'label' => 'Buttons',
                                'name' => 'multiple_button_row',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 2,
                                'max' => 0,
                                'layout' => 'row',
                                'button_label' => 'Add Buttons',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5985f18137fc5',
                                        'label' => 'Button Label',
                                        'name' => 'multiple_button_label',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5985f18137fc6',
                                        'label' => 'Button Class',
                                        'name' => 'multiple_button_class',
                                        'type' => 'text',
                                        'instructions' => 'Add a custom class name or attach the Popup Maker class',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5985f18137fc7',
                                        'label' => 'Button Link',
                                        'name' => 'multiple_button_link',
                                        'type' => 'url',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5985f18137fc9',
                                        'label' => 'Button Target',
                                        'name' => 'multiple_button_target',
                                        'type' => 'select',
                                        'instructions' => 'The target attribute specifies where to open the linked document.',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            '_self' => 'Current Tab',
                                            '_blank' => 'New Tab',
                                        ),
                                        'default_value' => array(
                                            0 => '_self',
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'return_format' => 'value',
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5985f18137fc8',
                                        'label' => 'Button Type',
                                        'name' => 'multiple_button_type',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'primary' => 'Primary',
                                            'secondary' => 'Secondary',
                                        ),
                                        'default_value' => array(
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'return_format' => 'value',
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5985f18137fca',
                                        'label' => 'Button Position',
                                        'name' => 'multiple_button_position',
                                        'type' => 'radio',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'left' => 'Left',
                                            'center' => 'Center',
                                            'right' => 'Right',
                                            'full' => 'Full',
                                        ),
                                        'allow_null' => 0,
                                        'other_choice' => 0,
                                        'save_other_choice' => 0,
                                        'default_value' => 'left',
                                        'layout' => 'vertical',
                                        'return_format' => 'value',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5979f7c78136a' => array(
                        'key' => '5979f7c78136a',
                        'name' => 'thumbnail_list',
                        'label' => 'Thumbnail List',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5979fc9404fa6',
                                'label' => 'Thumbnail Row',
                                'name' => 'thumbnail_row',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'row',
                                'button_label' => 'Add Item',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5979f83f8136c',
                                        'label' => 'Thumbnail Image',
                                        'name' => 'thumbnail_image',
                                        'type' => 'image',
                                        'instructions' => 'Recommended Image Size 150px Wide',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '25',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_5988afb83573a',
                                        'label' => 'Thumbnail Image Link',
                                        'name' => 'thumbnail_image_link',
                                        'type' => 'url',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_5979f86e8136d',
                                        'label' => 'Thumbnail Text',
                                        'name' => 'thumbnail_text',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '75',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5984b3af9b965' => array(
                        'key' => '5984b3af9b965',
                        'name' => 'partner_list',
                        'label' => 'Partner List',
                        'display' => 'table',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5984b3af9b966',
                                'label' => 'Partner Row',
                                'name' => 'partner_row',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => 'Add Row',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5984b3af9b967',
                                        'label' => 'Partner Image',
                                        'name' => 'partner_image',
                                        'type' => 'image',
                                        'instructions' => 'Recommended Image Size 100px Wide',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '25',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_5984b3af9b968',
                                        'label' => 'Partner Text',
                                        'name' => 'partner_text',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '75',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'basic',
                                        'media_upload' => 0,
                                        'delay' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5994876a06c8e',
                                        'label' => 'Partner Image Link',
                                        'name' => 'partner_image_link',
                                        'type' => 'url',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5979ff228f8e8' => array(
                        'key' => '5979ff228f8e8',
                        'name' => 'space',
                        'label' => 'Space',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5979ff228f8e9',
                                'label' => 'Space Height',
                                'name' => 'space_height',
                                'type' => 'number',
                                'instructions' => 'The height of the space in pixels',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 20,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    '5988b04f2ee64' => array(
                        'key' => '5988b04f2ee64',
                        'name' => 'video_embed',
                        'label' => 'Video',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5988b04f2ee65',
                                'label' => 'Video Embed Code',
                                'name' => 'video_embed_code',
                                'type' => 'textarea',
                                'instructions' => 'Paste in the video embed code',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_5cd1e6e40aa96' => array(
                        'key' => 'layout_5cd1e6e40aa96',
                        'name' => 'image_block_menu',
                        'label' => 'Image Block Menu',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5cd1eb27e86c8',
                                'label' => 'Block',
                                'name' => 'block',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5cd1e7a50aa9b',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                    ),
                                    array(
                                        'key' => 'field_5cd1e7070aa99',
                                        'label' => 'Image',
                                        'name' => 'image',
                                        'type' => 'image',
                                        'instructions' => 'Recommended: Uploaded an image greater than 600px wide (1:1 ratio). Any image that are not a 1:1 ratio will get auto cropped.',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_5cd1e72c0aa9a',
                                        'label' => 'Overlay Color',
                                        'name' => 'overlay_color',
                                        'type' => 'text',
                                        'instructions' => 'Defines the opacity as a number between 0.0 (fully transparent) and 1.0 (fully opaque)',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '255,0,0,0.3',
                                        'placeholder' => '255,0,0,0.3',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Add Block',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-full.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
            1 => 'excerpt',
            2 => 'discussion',
            3 => 'comments',
            4 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5cfef94a06e42',
        'title' => 'Calendar',
        'fields' => array(
            array(
                'key' => 'field_5cfef996872ad',
                'label' => 'Color',
                'name' => 'color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'calendar_type',
                ),
            ),
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'calendar_category',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_5cd4f84395e76',
        'title' => 'Deals',
        'fields' => array(
            array(
                'key' => 'field_5cd4f85563c40',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => 'Recommended: Uploaded an image greater than 600px wide (1:1 ratio). Any image that are not a 1:1 ration will get auto cropped.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5cd4f84c63c3f',
                'label' => 'Heading',
                'name' => 'heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cd4f85c63c41',
                'label' => 'Subheading',
                'name' => 'subheading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5cd4f86263c42',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'field_5cd4f87663c43',
                'label' => 'Body',
                'name' => 'body',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 0,
            ),
            array(
                'key' => 'field_5d25113a75d92',
                'label' => 'Featured',
                'name' => 'featured',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Featured',
                'ui_off_text' => 'Not Featured',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'deals',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_597fc9db70d60',
        'title' => 'Footer',
        'fields' => array(
            array(
                'key' => 'field_597fca032b0a6',
                'label' => 'Footer Call to Action',
                'name' => 'footer_call_to_action',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_597fca862b0a8',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_597fca862b0a8',
                        'label' => 'Icon',
                        'name' => 'footer_icon',
                        'type' => 'image',
                        'instructions' => 'Upload .svg file',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => 'svg',
                    ),
                    array(
                        'key' => 'field_597fcac72b0a9',
                        'label' => 'Label',
                        'name' => 'footer_icon_label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_597fcaef2b0aa',
                        'label' => 'URL',
                        'name' => 'footer_icon_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_597fcd37da2b6',
                'label' => 'Footer Text',
                'name' => 'footer_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-footer',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    acf_add_local_field_group(array(
        'key' => 'group_597fd3813c2cd',
        'title' => 'Social Media',
        'fields' => array(
            array(
                'key' => 'field_597fd387237fe',
                'label' => 'Social Media',
                'name' => 'social_media',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_597fd3a5237ff',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_597fd3a5237ff',
                        'label' => 'Social Media Icon',
                        'name' => 'social_media_icon',
                        'type' => 'image',
                        'instructions' => 'Upload .svg file',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_597fd3c423800',
                        'label' => 'Social Media Label',
                        'name' => 'social_media_label',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_597fd3df23801',
                        'label' => 'Social Media URL',
                        'name' => 'social_media_url',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;